config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#page'
  get 'home/page'

  resources :memes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meme.rb
class Meme < ApplicationRecord
    has_one_attached :image
    validates :image, presence: { message: " - Every meme needs to have an image" }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def page
  end
end

app/controllers/memes_controller.rb
class MemesController < ApplicationController
    before_action :set_meme, only: %i[ show edit update destroy ]
    before_action :authenticate_user!, only: %i[ new create edit update destroy ]
  
    # GET /memes or /memes.json
    def index
      @memes = Meme.all
    end
  
    # GET /memes/1 or /memes/1.json
    def show
    end
  
    # GET /memes/new
    def new
      @meme = Meme.new
    end
  
    # GET /memes/1/edit
    def edit
    end
  
    # POST /memes or /memes.json
    def create
      @meme = Meme.new(meme_params)
  
      respond_to do |format|
        if @meme.save
          format.html { redirect_to @meme, notice: "Meme was successfully created." }
          format.json { render :show, status: :created, location: @meme }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @meme.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # PATCH/PUT /memes/1 or /memes/1.json
    def update
      respond_to do |format|
        if @meme.update(meme_params)
          format.html { redirect_to @meme, notice: "Meme was successfully updated." }
          format.json { render :show, status: :ok, location: @meme }
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @meme.errors, status: :unprocessable_entity }
        end
      end
    end
  
    # DELETE /memes/1 or /memes/1.json
    def destroy
      @meme.destroy
      respond_to do |format|
        format.html { redirect_to memes_url, notice: "Meme was successfully destroyed." }
        format.json { head :no_content }
      end
    end
  
    private
      # Use callbacks to share common setup or constraints between actions.
      def set_meme
        @meme = Meme.find(params[:id])
      end
  
      # Only allow a list of trusted parameters through.
      def meme_params
        params.require(:meme).permit(:name, :description, :downloads, :price, :category, :image)
      end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/memes_helper.rb
module MemesHelper
end

app/views/Shared/_header.html.erb
<header id="top"> 
  <%= image_tag 'banner1' %>
</header>

app/views/Shared/_navbar.html.erb
<div class="home_buttons">

    <button class="btn btn-info" type="submit">
    <%= link_to 'Home', home_page_path %>
    </button>

    <button class="btn btn-info" type="submit">
    <%= link_to 'Add New Meme', new_meme_path %>
    </button>

    <button class="btn btn-info" type="submit">
    <%= link_to 'Show All Memes', memes_path %>
    </button>

    <button class="btn btn-info" type="submit">
    <%= link_to 'Register New User', new_user_registration_path %>
    </button>

<% if user_signed_in? %>
    <button class="btn btn-info" type="submit">
    <%= link_to 'Log Out', destroy_user_session_path, method: :delete %>
    </button>
<% end %>

<% if !user_signed_in? %>
    <button class="btn btn-info" type="submit">
    <%= link_to 'Log In', new_user_session_path %>
    </button>
<% end %>

app/views/home/page.html.erb
<%= image_tag 'home_page_meme', class: "centre" %>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meme Library</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    <%= render 'Shared/header' %>
    <br>
    <%= render 'Shared/navbar' %>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
  </body>
</html>

app/views/memes/_form.html.erb
<%= form_with(model: meme) do |form| %>
  <% if meme.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meme.errors.count, "error") %> prohibited this meme from being saved:</h2>

      <ul>
        <% meme.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <%# <div class="field">
    <%= form.label :downloads %>
    <%# <%= form.number_field :downloads %>
  <%# </div> %>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :keyword %>
    <%= form.text_field :keyword %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, accept: 'image/png, image/jpg, image/jpeg, image/webp' %>
  </div>

  <br>

  <div class="actions">
    <%= form.submit %>
  </div>

    <br>

<% end %>

app/views/memes/edit.html.erb
<h1>Edit Your Meme</h1>

<%= render 'form', meme: @meme %>

<%# <%= link_to 'Show', @meme %> 
<%# <%= link_to 'Back', memes_path %> 

app/views/memes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Memes</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <%# <th>Downloads</th> %>
      <th>Price</th>
      <th>Image</th>
      <%# <th>Category</th> %>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @memes.each do |meme| %>
      <tr>
        <td><%= meme.name %></td>

        <td><%= meme.description %></td>
        <%# <td><%= meme.downloads %>
        <td><%= meme.price %></td>
        <%# <td><%= meme.category %>
        <td><%= image_tag meme.image %></td>
        <td><%= link_to 'Show', meme %></td>
        <td><%= link_to 'Edit', edit_meme_path(meme) %></td>
        <td><%= link_to 'Destroy', meme, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%# <%= link_to 'New Meme', new_meme_path %>

app/views/memes/new.html.erb
<h1>New Meme</h1>

<%= render 'form', meme: @meme %>

<%# <%= link_to 'Back', memes_path %>

app/views/memes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @meme.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @meme.description %>
</p>

<%# <p>
  <strong>Downloads:</strong>
  <%= @meme.downloads %>
<%# </p> %>

<p>
  <strong>Price: $</strong>
  <%= @meme.price %>
</p>

<%# <p>
  <strong>Category:</strong>
  <%= @meme.category %>
<%# </p> %>
<p>
<%= image_tag @meme.image %>
</p>

<br>

<%= link_to 'Edit', edit_meme_path(@meme) %> |
<%= link_to 'Back', memes_path %>

<br>